# Generated by Django 5.1.2 on 2024-10-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('Equity', 'Equity'), ('Fixed_Income', 'Fixed Income'), ('Commodities', 'Commodities'), ('Crypto', 'Crypto'), ('Forex', 'Forex')], default='Equity', max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=10)),
                ('identify_date', models.DateField()),
                ('strategy', models.CharField(max_length=255)),
                ('entry_date', models.DateField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_date', models.DateField()),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days', models.IntegerField()),
                ('status', models.CharField(choices=[('Trailing_SL', 'Trailing SL'), ('Stop_loss_hit', 'Stop loss hit'), ('Running_profits', 'Running profits'), ('Target_hit', 'Target hit'), ('Near_target', 'Near target'), ('Waiting_for_entry', 'Waiting for ENTRY signal'), ('Holding', 'Holding'), ('Near_stop_loss', 'Near Stop Loss')], default='Waiting_for_entry', max_length=20)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('technicals', models.TextField()),
                ('fundamentals', models.TextField()),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('take_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk_reward_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pre_trade_emotions', models.TextField()),
                ('in_trade_emotions', models.TextField()),
                ('post_trade_emotions', models.TextField()),
                ('lessons_learned', models.TextField()),
            ],
        ),
    ]
