# Generated by Django 5.1.2 on 2024-10-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeentry',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('PAK', 'PAK'), ('UAE', 'UAE')], default='PAK', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='days',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='fundamentals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='identify_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='in_trade_emotions',
            field=models.CharField(blank=True, choices=[('Confident', 'Confident'), ('Excited', 'Excited'), ('Nervous', 'Nervous'), ('Fearful', 'Fearful'), ('Greedy', 'Greedy'), ('Impatient', 'Impatient'), ('Relaxed', 'Relaxed'), ('Doubtful', 'Doubtful'), ('Indifferent', 'Indifferent'), ('Optimistic', 'Optimistic'), ('Pessimistic', 'Pessimistic'), ('Overconfident', 'Overconfident'), ('Curious', 'Curious')], default='Confident', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='lessons_learned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='post_trade_emotions',
            field=models.CharField(blank=True, choices=[('Confident', 'Confident'), ('Excited', 'Excited'), ('Nervous', 'Nervous'), ('Fearful', 'Fearful'), ('Greedy', 'Greedy'), ('Impatient', 'Impatient'), ('Relaxed', 'Relaxed'), ('Doubtful', 'Doubtful'), ('Indifferent', 'Indifferent'), ('Optimistic', 'Optimistic'), ('Pessimistic', 'Pessimistic'), ('Overconfident', 'Overconfident'), ('Curious', 'Curious')], default='Confident', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='pre_trade_emotions',
            field=models.CharField(blank=True, choices=[('Confident', 'Confident'), ('Excited', 'Excited'), ('Nervous', 'Nervous'), ('Fearful', 'Fearful'), ('Greedy', 'Greedy'), ('Impatient', 'Impatient'), ('Relaxed', 'Relaxed'), ('Doubtful', 'Doubtful'), ('Indifferent', 'Indifferent'), ('Optimistic', 'Optimistic'), ('Pessimistic', 'Pessimistic'), ('Overconfident', 'Overconfident'), ('Curious', 'Curious')], default='Confident', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='technicals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
