# Generated by Django 5.1.2 on 2024-10-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_tradeentry_macro_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeentry',
            name='stop_loss',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tradeentry',
            name='take_profit',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
